spring.application.name=sugoonaboxd

spring.datasource.url=jdbc:postgresql://imidb.f4.htw-berlin.de:5432/s0579116
spring.datasource.username=s0579116
spring.datasource.password=xe6Chaic

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
